/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7e1cd906e8563f3229ad2d
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ClassesService } from '../../services/classes.service';
import { ExamService } from '../../services/exam.service';
import { TeacherService } from '../../services/teacher.service';
import { StudentService } from '../../services/student.service';
// Import Models
import { Classes } from '../../domain/shri-dev-pathshal-a_db/classes';
import { Exam } from '../../domain/shri-dev-pathshal-a_db/exam';
import { Student } from '../../domain/shri-dev-pathshal-a_db/student';
import { Teacher } from '../../domain/shri-dev-pathshal-a_db/teacher';

// START - USED SERVICES
/**
* ClassesService.create
*	@description CRUD ACTION create
*
* ClassesService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* ClassesService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* ExamService.findBy_Class
*	@description CRUD ACTION findBy_Class
*	@param Objectid key Id of model to search for
*
* TeacherService.findBy_Classes
*	@description CRUD ACTION findBy_Classes
*	@param Objectid key Id of model to search for
*
* StudentService.findBy_Classes
*	@description CRUD ACTION findBy_Classes
*	@param Objectid key Id of model to search for
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Classes
 */
@Component({
    selector: 'app-classes-edit',
    templateUrl: 'classes-edit.component.html',
    styleUrls: ['classes-edit.component.css']
})
export class ClassesEditComponent implements OnInit {
    item: Classes;
    externalExam__Class: Exam[];
    externalStudent__Classes: Student[];
    externalTeacher__Classes: Teacher[];
    model: Classes;
    formValid: Boolean;

    constructor(
    private classesService: ClassesService,
    private examService: ExamService,
    private teacherService: TeacherService,
    private studentService: StudentService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Classes();
        this.externalExam__Class = [];
        this.externalStudent__Classes = [];
        this.externalTeacher__Classes = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.classesService.get(id).subscribe(item => this.item = item);
                this.examService.findBy_Class(id).subscribe(list => this.externalExam__Class = list);
                this.studentService.findBy_Classes(id).subscribe(list => this.externalStudent__Classes = list);
                this.teacherService.findBy_Classes(id).subscribe(list => this.externalTeacher__Classes = list);
            }
            // Get relations
        });
    }


    /**
     * Save Classes
     *
     * @param {boolean} formValid Form validity check
     * @param Classes item Classes to save
     */
    save(formValid: boolean, item: Classes): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.classesService.update(item).subscribe(data => this.goBack());
            } else {
                this.classesService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



