/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7e1cd906e8563f3229ad2d
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { StudentService } from '../../services/student.service';
import { ExamService } from '../../services/exam.service';
import { ClassesService } from '../../services/classes.service';
// Import Models
import { Student } from '../../domain/shri-dev-pathshal-a_db/student';
import { Classes } from '../../domain/shri-dev-pathshal-a_db/classes';
import { Exam } from '../../domain/shri-dev-pathshal-a_db/exam';

// START - USED SERVICES
/**
* StudentService.create
*	@description CRUD ACTION create
*
* StudentService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* StudentService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* ExamService.findBy_Student
*	@description CRUD ACTION findBy_Student
*	@param Objectid key Id of model to search for
*
* ClassesService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Student
 */
@Component({
    selector: 'app-student-edit',
    templateUrl: 'student-edit.component.html',
    styleUrls: ['student-edit.component.css']
})
export class StudentEditComponent implements OnInit {
    item: Student;
    list_Classes: Classes[];
    externalExam__Student: Exam[];
    model: Student;
    formValid: Boolean;

    constructor(
    private studentService: StudentService,
    private examService: ExamService,
    private classesService: ClassesService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Student();
        this.externalExam__Student = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.studentService.get(id).subscribe(item => this.item = item);
                this.examService.findBy_Student(id).subscribe(list => this.externalExam__Student = list);
            }
            // Get relations
            this.classesService.list().subscribe(list => this.list_Classes = list);
        });
    }

    /**
     * Check if an Classes is in  _Classes
     *
     * @param {string} id Id of Classes to search
     * @returns {boolean} True if it is found
     */
    containClasses(id: string): boolean {
        if (!this.item._Classes) return false;
        return this.item._Classes.indexOf(id) !== -1;
    }

    /**
     * Add Classes from Student
     *
     * @param {string} id Id of Classes to add in this.item._Classes array
     */
    addClasses(id: string) {
        if (!this.item._Classes)
            this.item._Classes = [];
        this.item._Classes.push(id);
    }

    /**
     * Remove an Classes from a Student
     *
     * @param {number} index Index of Classes in this.item._Classes array
     */
    removeClasses(index: number) {
        this.item._Classes.splice(index, 1);
    }

    /**
     * Save Student
     *
     * @param {boolean} formValid Form validity check
     * @param Student item Student to save
     */
    save(formValid: boolean, item: Student): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.studentService.update(item).subscribe(data => this.goBack());
            } else {
                this.studentService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



