/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7e1cd906e8563f3229ad2d
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ExamService } from '../../services/exam.service';
// Import Models
import { Exam } from '../../domain/shri-dev-pathshal-a_db/exam';

// START - USED SERVICES
/**
* ExamService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* ExamService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Exam
 * @class ExamListComponent
 */
@Component({
    selector: 'app-exam-list',
    templateUrl: './exam-list.component.html',
    styleUrls: ['./exam-list.component.css']
})
export class ExamListComponent implements OnInit {
    list: Exam[];
    search: any = {};
    idSelected: string;
    constructor(
        private examService: ExamService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.examService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Exam to remove
     *
     * @param {string} id Id of the Exam to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Exam
     */
    deleteItem() {
        this.examService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
