/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7e1cd906e8563f3229ad2d
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { TeacherService } from '../../services/teacher.service';
// Import Models
import { Teacher } from '../../domain/shri-dev-pathshal-a_db/teacher';

// START - USED SERVICES
/**
* TeacherService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* TeacherService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Teacher
 * @class TeacherListComponent
 */
@Component({
    selector: 'app-teacher-list',
    templateUrl: './teacher-list.component.html',
    styleUrls: ['./teacher-list.component.css']
})
export class TeacherListComponent implements OnInit {
    list: Teacher[];
    search: any = {};
    idSelected: string;
    constructor(
        private teacherService: TeacherService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.teacherService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Teacher to remove
     *
     * @param {string} id Id of the Teacher to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Teacher
     */
    deleteItem() {
        this.teacherService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
